CREATE TABLE `CUSTOMER` (
  `cusname` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `place` varchar(30) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `DESIGN` (
  `DN_NO` int(11) NOT NULL,
  `NAME` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `CLOTH_TYPE` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `BASIC_COST` int(11) DEFAULT NULL,
  `WORK_COST` int(11) DEFAULT NULL,
  `LACE_COST` int(11) DEFAULT NULL,
  `DIAMOND_COST` int(11) DEFAULT NULL,
  `PACKING_COST` int(11) DEFAULT NULL,
  `MU` int(11) DEFAULT NULL,
  `CALC_PRICE` int(11) GENERATED ALWAYS AS ((`BASIC_COST` + `WORK_COST` + `LACE_COST` + `DIAMOND_COST` + `PACKING_COST`) * 100 / (100 - `MU`)) VIRTUAL,
  `WORK_JOB` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LACE_JOB` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DIAM_JOB` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `SALES_ORDER` (
  `BILL_NO` int(11) NOT NULL,
  `CNAME` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ORDER_DATE` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `SALES_ORDER_DETAILS` (
  `BILL_NO` int(11) DEFAULT NULL,
  `NAME` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `QTY` int(11) DEFAULT NULL,
  `RATE` int(11) DEFAULT NULL,
  `TYPE` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `DESIGN`
  ADD PRIMARY KEY (`DN_NO`,`NAME`);

ALTER TABLE `SALES_ORDER`
  ADD PRIMARY KEY (`BILL_NO`);
COMMIT;
